-- MySQL Script generated by MySQL Workbench
-- Sun Mar  8 22:19:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sales` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `sales` ;

-- -----------------------------------------------------
-- Table `sales`.`sanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`sanpham` (
  `idsanpham` INT NOT NULL,
  `tensanpham` VARCHAR(100) NULL,
  `mausac` VARCHAR(45) NULL,
  `dungtich` VARCHAR(100) NULL,
  `sanphamcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idsanpham`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
